### ISSUE TITLE
Warning: unknown message type 105 from VNC server

### ISSUE THREAD

**Issue by wassilis83** [IDNT/vncsnapshot#1]
I'm using this project for a personal control platform and is working very good, but each time I run vncsnapshot(can be from linux or windows) I always receive this:

```
Warning: unknown message type 105 from VNC server
Warning: unknown message type 116 from VNC server
Warning: unknown message type 45 from VNC server
Warning: unknown message type 100 from VNC server
Warning: unknown message type 101 from VNC server
Warning: unknown message type 112 from VNC server
Warning: unknown message type 97 from VNC server
Warning: unknown message type 114 from VNC server
Warning: unknown message type 116 from VNC server
Warning: unknown message type 109 from VNC server
Warning: unknown message type 101 from VNC server
Warning: unknown message type 110 from VNC server
Warning: unknown message type 116 from VNC server
Warning: unknown message type 45 from VNC server
Warning: unknown message type 112 from VNC server
```

but snapshots are good so it's ok, just a little annoying. Is there a way to fix this? I'm using as servers latest tyghtvnc 2.8.81

**Comment by mazocode** [comment]
This is shown for every server to client message we did not handle. You can safely remove the message from here:

https://github.com/IDNT/vncsnapshot/blob/53ecbdf36b0058e68bfa9af46461c50e798d328f/rfbproto.c#L734

Details can be found here: https://www.iana.org/assignments/rfb/rfb.xhtml
